AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Lambda Auth function"

Parameters:
  S3BucketName:
    Type: String
    Description: Name of S3 bucket containing Lambda code
    Default: eml-artifacts-bucket
  S3Key:
    Type: String
    Description: S3 key/path to Lambda function code
    Default: services/Auth/aws_lambda_auth.zip
  ProjectPrefix:
    Type: String
    Description: Prefix for the project resources
    Default: eml
  ProjectName:
    Type: String
    Description: Name of the project for which the Lambda function is being created
    Default: EchoMateLite
  Environment:
    Type: String
    Description: Environment for which the Lambda function is being created (e.g., dev, prod)
    Default: dev
    AllowedValues:
      - dev
      - prod
  ElastiCacheEndpoint:
    Type: String
    Description: Endpoint for the ElastiCache Redis instance
  ElastiCachePort:
    Type: String
    Description: Port for the ElastiCache Redis instance
    Default: "6379"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  AuthFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-auth-function"
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          STACK_NAME: !Ref AWS::StackName
          USER_POOL_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolId"
          USER_POOL_CLIENT_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolClientId"
          ElastiCacheEndpoint: !Ref ElastiCacheEndpoint
          ElastiCachePort: !Ref ElastiCachePort

  # LambdaLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub "/aws/lambda/${ProjectPrefix}-auth-function"
  #     RetentionInDays: 30
  #     DependsOn: LambdaExecutionRole
Outputs:
  AuthFunctionArn:
    Description: ARN of the Auth Lambda function
    Value: !GetAtt AuthFunction.Arn
    Export:
      Name: !Sub "${ProjectPrefix}-AuthFunctionArn"
  AuthFunctionName:
    Description: Name of the Auth Lambda function
    Value: !Ref AuthFunction
    Export:
      Name: !Sub "${ProjectPrefix}-AuthFunctionName"
