AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function with API Gateway trigger and S3 source code"

Parameters:
  S3BucketName:
    Type: String
    Description: Name of S3 bucket containing Lambda source code
  S3Key:
    Type: String
    Description: S3 key for Lambda source code zip file
  ProjectName:
    Type: String
    Description: Name of the project
  ProjectPrefix:
    Type: String
    Description: Name of the project prefix
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - prod

Resources:
  EmlLoginLambdaExecutionRole:
    Type: AWS::IAM::Role 
    Properties:
      RoleName: !Sub "${ProjectPrefix}-LoginLambdaExecutionRole"
      Description: Role for Lambda execution
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ElastiCacheAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticache:Connect
                  - elasticache:CreateCacheCluster
                  - elasticache:DescribeCacheClusters
                  - elasticache:ModifyCacheCluster
                Resource: "*"
  EmlLoginLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-login-function"
      Handler: index.handler
      Description: Lambda function for EML registration
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Handler: index.handler
      Role: !GetAtt EmlLoginLambdaExecutionRole.Arn
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          PROJECT_NAME: !Ref ProjectName
          PROJECT_PREFIX: !Ref ProjectPrefix
          ENVIRONMENT: !Ref Environment
          USER_POOL_CLIENT_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolClientId"
          USER_POOL_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolId"
          MY_AWS_REGION: !Ref AWS::Region
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: ProjectPrefix
          Value: !Ref ProjectPrefix
        - Key: Environment
          Value: !Ref Environment

  # API Gateway resource for registration
  EmlApiGatewayLoginResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue eml-ApiResourceId
      PathPart: "Login"
      RestApiId: !ImportValue eml-RestApiId

  # API Gateway method for registration
  EmlApiGatewayLoginMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref EmlApiGatewayLoginResource
      RestApiId: !ImportValue eml-RestApiId
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmlLoginLambdaFunction.Arn}/invocations

  # API Gateway deployment
  EmlApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - EmlApiGatewayLoginMethod
    Properties:
      RestApiId: !ImportValue eml-RestApiId
      StageName: !Ref Environment

  # API Gateway permission for Lambda function
  EmlLambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EmlLoginLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayID}/*/POST/*
        - ApiGatewayID: !ImportValue eml-RestApiId

Outputs:
  EmlApiEndpointForLogin:
    Description: API Gateway endpoint URL
    Value: !Sub
      - https://${ApiGatewayID}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/Login
      - ApiGatewayID: !ImportValue eml-RestApiId
    Export:
      Name: !Sub "${ProjectPrefix}-LoginEndpoint"
  EmlLambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt EmlLoginLambdaFunction.Arn
    Export:
      Name: !Sub "${ProjectPrefix}-LoginFunctionArn"
