AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function with API Gateway trigger and S3 source code"

Parameters:
  S3BucketName:
    Type: String
    Description: Name of S3 bucket containing Lambda source code
  S3Key:
    Type: String
    Description: S3 key for Lambda source code zip file
  ProjectName:
    Type: String
    Description: Name of the project
  ProjectPrefix:
    Type: String
    Description: Name of the project prefix
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - prod

Resources:
  RegisterLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-RegisterLambdaExecutionRole"
      Description: Role for Lambda execution
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  EmlRegisterLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-register-function"
      Description: Lambda function for EML registration
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Handler: index.handler
      Role: !GetAtt RegisterLambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          PROJECT_NAME: !Ref ProjectName
          PROJECT_PREFIX: !Ref ProjectPrefix
          ENVIRONMENT: !Ref Environment
          USER_POOL_CLIENT_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolClientId"
          USER_POOL_ID: !ImportValue
            Fn::Sub: "${ProjectPrefix}-UserPoolId"
          MY_AWS_REGION: !Ref AWS::Region
          DYNAMO_DB_TABLE_NAME: !ImportValue
            Fn::Sub: "${ProjectPrefix}-DynamoDBTableForUserDetails"

      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: ProjectPrefix
          Value: !Ref ProjectPrefix
        - Key: Environment
          Value: !Ref Environment

  # API Gateway resource for registration
  EmlApiGatewayRegisterResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !ImportValue eml-ApiResourceId
      PathPart: "register"
      RestApiId: !ImportValue eml-RestApiId

  # API Gateway resource for email verification
  EmlApiGatewayEmailVerificationResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref EmlApiGatewayRegisterResource
      PathPart: "email-verification"
      RestApiId: !ImportValue eml-RestApiId

  # API Gateway OPTIONS method for registration
  EmlApiGatewayRegisterOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseTemplates:
              application/json: "{}"
            StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      ResourceId: !Ref EmlApiGatewayRegisterResource
      RestApiId: !ImportValue eml-RestApiId
      MethodResponses:
        - ResponseModels:
            application/json: "Empty"
          StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Credentials: false

  # API Gateway OPTIONS method for email verification
  EmlApiGatewayEmailVerificationOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
        IntegrationResponses:
          - ResponseTemplates:
              application/json: "{}"
            StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
          ResponceParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Credentials: "'true'"
      ResourceId: !Ref EmlApiGatewayEmailVerificationResource
      RestApiId: !ImportValue eml-RestApiId
      MethodResponses:
        - ResponseModels:
            application/json: "Empty"
          StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Credentials: false

  # API Gateway method for registration
  EmlApiGatewayRegisterPOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref EmlApiGatewayRegisterResource
      RestApiId: !ImportValue eml-RestApiId
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmlRegisterLambdaFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true

  # API Gateway method for registration
  EmlApiGatewayEmailVerificationPOSTMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref EmlApiGatewayEmailVerificationResource
      RestApiId: !ImportValue eml-RestApiId
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmlRegisterLambdaFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true

  # API Gateway deployment
  EmlApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - EmlApiGatewayRegisterPOSTMethod
      - EmlApiGatewayEmailVerificationPOSTMethod
    Properties:
      RestApiId: !ImportValue eml-RestApiId
      StageName: !Ref Environment

  # API Gateway permission for Lambda function
  EmlLambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EmlRegisterLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayID}/*/POST/*
        - ApiGatewayID: !ImportValue eml-RestApiId

Outputs:
  EmlApiEndpointForRegister:
    Description: API Gateway endpoint URL
    Value: !Sub
      - https://${ApiGatewayID}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/register
      - ApiGatewayID: !ImportValue eml-RestApiId
    Export:
      Name: !Sub "${ProjectPrefix}-RegisterEndpoint"
  EmlApiEndpointForEmailVerification:
    Description: API Gateway endpoint URL for email verification
    Value: !Sub
      - https://${ApiGatewayID}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/register/email-verification
      - ApiGatewayID: !ImportValue eml-RestApiId
    Export:
      Name: !Sub "${ProjectPrefix}-EmailVerificationEndpoint"
  EmlLambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt EmlRegisterLambdaFunction.Arn
    Export:
      Name: !Sub "${ProjectPrefix}-RegisterLambdaFunctionArn"
