# Stage 1: Build
FROM node:22-alpine AS build
WORKDIR /usr/app

# Copy package files first to leverage Docker cache
COPY ./eml_ui/package*.json ./
RUN npm ci --quiet

# Copy the rest of the application
COPY ./eml_ui .

# Build the application
RUN npm run build

# Stage 2: Final (production)
FROM nginx:alpine AS final

# Copy built files and configuration
COPY --from=build /usr/app/dist /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
