AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template create RESTFull API, S3 bucket, and DynamoDB table.
Parameters:
  ProjectPrefix:
    Type: String
    Description: The project prefix for the resources.
    Default: eml

  ProjectName:
    Type: String
    Description: The name of the project.
    Default: EmailMateLite

Resources:
  DynamoDBTableForUserDetails:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-UserDetails"
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: FirstName
          AttributeType: S
        - AttributeName: MiddleName
          AttributeType: S
        - AttributeName: LastName
          AttributeType: S
        - AttributeName: EmailId
          AttributeType: S
        - AttributeName: PhoneNumber
          AttributeType: S
        - AttributeName: Address
          AttributeType: M
        - AttributeName: DateOfBirth
          AttributeType: S
        - AttributeName: Gender
          AttributeType: S
        - AttributeNmae: DateOfJoining
          AttributeType: S
        - AttributeName: IsDeleted
          AttributeType: BOOL
          Default: false
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EmlDynamoDBTableForPosts:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-Posts"
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: PostId
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
        - AttributeName: Message
          AttributeType: S
        - AttributeName: Images
          AttributeType: array
        - AttributeName: Likes
          AttributeType: N
        - AttributeName: Comments
          AttributeType: M
        - AttributeName: IsDeleted
          AttributeType: BOOL
          Default: false
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: PostId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EmlDynamoDBTableForImageDetails:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-ImageDetails"
      AttributeDefinitions:
        - AttributeName: ParentId
          AttributeType: S
        - AttributeName: ImageId
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
        - AttributeName: IsDeleted
          AttributeType: BOOL
          Default: false
      KeySchema:
        - AttributeName: ParentId
          KeyType: HASH
        - AttributeName: ImageId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  EmlDynamoDBTableForUserDetailsOutput:
    Description: DynamoDB table name for user details.
    Value: !Ref DynamoDBTableForUserDetails
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForUserDetailsOutput"

  EmlDynamoDBTableForPostsOutput:
    Description: DynamoDB table name for posts.
    Value: !Ref EmlDynamoDBTableForPosts
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForPostsOutput"

  EmlDynamoDBTableForImageDetailsOutput:
    Description: DynamoDB table name for image details.
    Value: !Ref EmlDynamoDBTableForImageDetails
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForImageDetailsOutput"
