AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates RESTful API, S3 bucket, and DynamoDB tables.
Parameters:
  ProjectPrefix:
    Type: String
    Description: The project prefix for the resources.
    Default: eml
    MinLength: 1
    MaxLength: 10
    AllowedPattern: "[a-zA-Z0-9-]*"

  ProjectName:
    Type: String
    Description: The name of the project.
    Default: EmailMateLite
    MinLength: 1
    AllowedPattern: "[a-zA-Z0-9-]*"

Resources:
  DynamoDBTableForUserDetails:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-UserDetails"
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      DeletionPolicy: Retain
      BillingMode: PAY_PER_REQUEST

  EmlDynamoDBTableForPosts:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-Posts"
      AttributeDefinitions:
        - AttributeName: PostId
          AttributeType: S
      KeySchema:
        - AttributeName: PostId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      DeletionPolicy: Retain
      BillingMode: PAY_PER_REQUEST

  EmlDynamoDBTableForImageDetails:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-ImageDetails"
      AttributeDefinitions:
        - AttributeName: ImageId
          AttributeType: S
      KeySchema:
        - AttributeName: ImageId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      DeletionPolicy: Retain
      BillingMode: PAY_PER_REQUEST

Outputs:
  EmlDynamoDBTableForUserDetailsOutput:
    Description: DynamoDB table name for user details.
    Value: !Ref DynamoDBTableForUserDetails
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForUserDetailsOutput"

  EmlDynamoDBTableForPostsOutput:
    Description: DynamoDB table name for posts.
    Value: !Ref EmlDynamoDBTableForPosts
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForPostsOutput"

  EmlDynamoDBTableForImageDetailsOutput:
    Description: DynamoDB table name for image details.
    Value: !Ref EmlDynamoDBTableForImageDetails
    Export:
      Name: !Sub "${ProjectPrefix}-DynamoDBTableForImageDetailsOutput"
