pipeline{
    agent any
    environment{
        
    }
    stages{
        stage('Validating CloudFormation Template'){
            steps{
                echo 'Start: Validating the CloudFormation template...'
                sh """
                    echo 'Validating Services_Roles_CF'
                    aws cloudformation validate-template --template-body file://Network_CF.yml
                """
                sh """
                    echo 'Validating Services_CF'
                    aws cloudformation validate-template --template-body file://Services_Roles_CF.yml
                """
            }
        }
        stage('Deploying the CFN Stack'){
            steps{
                echo 'Start: Deploying the CloudFormation stack...'
                def stackName = 'Services_Roles_CFN'
                if (sh "aws cloudformation describe-stacks --stack-name ${stackName}" == 0){
                    echo 'Stack already exists. Updating the stack...'
                    sh """
                        echo 'Updating Services_Roles_CF'
                        aws cloudformation update-stack --stack-name Services_Roles_CF --template-body file://${stackName}.yml  --capabilities CAPABILITY_NAMED_IAM
                    """
                } else {
                    echo 'Stack does not exist. Creating the stack...'
                    sh """
                        echo 'Deploying Services_Roles_CF'
                        aws cloudformation create-stack --stack-name Services_Roles_CF --template-body file://${stackName}.yml --parameters file://Services_Roles_CF_Parameters.json --capabilities CAPABILITY_NAMED_IAM
                    """
                }
            }
            steps{
                echo 'Start: Deploying the CloudFormation stack...'
                def stackName = 'Services_CFN'
                if (sh "aws cloudformation describe-stacks --stack-name ${stackName}" == 0){
                    echo 'Stack already exists. Updating the stack...'
                    sh """
                        echo 'Updating Network_CF'
                        aws cloudformation update-stack --stack-name Network_CF --template-body file://${stackName}.yml  --capabilities CAPABILITY_NAMED_IAM
                    """
                } else {
                    echo 'Stack does not exist. Creating the stack...'
                    sh """
                        echo 'Deploying Network_CF'
                        aws cloudformation create-stack --stack-name Network_CF --template-body file://${stackName}.yml --parameters file://Network_CF_Parameters.json --capabilities CAPABILITY_NAMED_IAM
                    """
                }
            }
        }
    }
}