AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template create RESTFull API, and S3 bucket
Parameters:
  ProjectPrefix:
    Type: String
    Description: Input project name.
    Default: eml
  ProjectName:
    Type: String
    Description: Input project name.
    Default: EchoMateLite
  Environment:
    Type: String
    Description: Input stage name.
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
Resources:
  # Rest API
  EmlRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectPrefix}-RestApi"
      Description: !Sub "This is the REST API for ${ProjectName}"
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectPrefix
          Value: !Ref ProjectPrefix
        - Key: Name
          Value: !Sub "${ProjectPrefix}-RestApi"

Outputs:
  # Rest API Outputs
  EmlRestApiId:
    Description: RESTFull API ID.
    Value: !Ref EmlRestApi
    Export:
      Name: !Sub "${ProjectPrefix}-RestApiId"
  EmlRestApiName:
    Description: RESTFull API name.
    Value: !Sub "${ProjectPrefix}-${Environment}-RestApi"
    Export:
      Name: !Sub "${ProjectPrefix}-RestApiName"
  EmlRestApiEndpoint:
    Description: RESTFull API endpoint.
    Value: !Sub "https://${EmlRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${ProjectPrefix}-RestApiEndpoint"
