AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template create RESTFull API, S3 bucket and ElastiCache.
Parameters:
  ProjectName:
    Type: String
    Description: Input project name.
  Stage:
    Type: String
    Description: Input stage name.
    AllowedValues:
      - dev
      - prod
  S3BucketName:
    Type: String
    Description: Input S3 bucket name.
  DynamoDBTableNameForUserDetails:
    Type: String
    Description: Input DynamoDB table name.
  DynamoDBTableNameForImageDetails:
    Type: String
    Description: Input DynamoDB table name.
Resources:
  EmlS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  EmlElastiCache:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1
      
  EmlRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join ["", [!Ref ProjectName, "-", !Ref Stage]]

Outputs:
  EmlS3BucketArn:
    Description: S3 bucket name.
    Value: !GetAtt EmlS3Bucket.Arn
  EmlDynamoDBTableForUserDetailsOutput:
    Description: DynamoDB table name for user details.
    Value: !Ref EmlDynamoDBTableForUserDetails
  EmlDynamoDBTableForImageDetailsOutput:
    Description: DynamoDB table name for image details.
    Value: !Ref EmlDynamoDBTableForImageDetails
  EmlRestApiOutput:
    Description: RESTFull API name.
    Value: !Ref EmlRestApi
